"""U67: the committed API reference matches what the running API actually serves.

docs/public/reference/openapi.json is generated by platform/api/generate_openapi.py,
from the FastAPI app's own route definitions, and docs/public/reference/
api-reference.html is rendered from it by docs/tools/generate_api_reference.py.
Neither is hand-written, but a
generated file committed to the repo can still go stale if someone changes a
route and forgets to regenerate it. This compares the checked-in file against
FastAPI's own live /openapi.json on the running instance, which is the same
schema `generate_openapi.py` would produce from the same code, so a mismatch
means the committed copy is out of date rather than that the two generators
disagree.

    docker compose exec -T munitas-api python /verify/v67_openapi_current.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from common import check, heading, require_api, summary, api

DOCS_OPENAPI = Path(__file__).parent.parent / "docs" / "public" / "reference" / "openapi.json"


def normalize(schema: dict) -> str:
    # Compare structure, not formatting: generate_openapi.py sorts keys and
    # indents for readability, but that's irrelevant to whether the schema
    # itself is current.
    return json.dumps(schema, sort_keys=True)


def main() -> int:
    require_api()
    heading("U67: committed docs/public/reference/openapi.json matches the live schema")

    if not DOCS_OPENAPI.exists():
        check(
            "docs/public/reference/openapi.json exists",
            False,
            f"not found at {DOCS_OPENAPI}. Run platform/api/generate_openapi.py first.",
        )
        return summary("U67")

    committed = json.loads(DOCS_OPENAPI.read_text(encoding="utf-8"))

    resp = api("GET", "/openapi.json")
    check("GET /openapi.json succeeds", resp.status_code == 200, resp.text[:200])
    if resp.status_code != 200:
        return summary("U67")

    live = resp.json()

    committed_paths = set(committed.get("paths", {}))
    live_paths = set(live.get("paths", {}))
    check(
        "no paths missing from the committed reference",
        live_paths <= committed_paths,
        f"live has paths not in docs/public/reference/openapi.json: {sorted(live_paths - committed_paths)}",
    )
    check(
        "no stale paths left in the committed reference",
        committed_paths <= live_paths,
        f"docs/public/reference/openapi.json has paths the live API no longer serves: {sorted(committed_paths - live_paths)}",
    )
    # The detail is only the repair instruction when there is something to
    # repair. Printed unconditionally, as it was, a passing run reads
    # "matches the live schema exactly (structurally different)", which says
    # the opposite of the result beside it.
    matches = normalize(committed) == normalize(live)
    check(
        "committed schema matches the live schema exactly",
        matches,
        "in step" if matches else
        "structurally different -- re-run platform/api/generate_openapi.py "
        "and docs/tools/generate_api_reference.py and commit the result.",
    )

    return summary("U67")


if __name__ == "__main__":
    sys.exit(main())
