"""Worker configuration.

The worker runs on the host and talks to Compose services over published ports,
so every address here is localhost. Inside the containers the same services are
reached by service name, which is why these are not shared with the API's config.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

# No .resolve() here on purpose: this module is imported by
# worker/dag_workflow.py, a Temporal workflow definition, whose sandbox
# intercepts every import in its dependency chain and blocks
# Path.resolve() as a non-deterministic filesystem call (confirmed live --
# starting the worker for real raised RestrictedWorkflowAccessError the
# first time this used .resolve()). __file__ is already absolute for a
# normally-imported module, so .parent.parent alone is sandbox-safe too.
sys.path.insert(0, str(Path(__file__).parent.parent))
from ports_config import PORTS  # noqa: E402

API = os.environ.get("MUNITAS_API", f"http://localhost:{PORTS['munitas_api_http']}")
TEMPORAL = os.environ.get("TEMPORAL_ADDRESS", f"localhost:{PORTS['temporal']}")

# A self-signed certificate this worker should trust for API, beyond the
# system trust store -- set when MUNITAS_API points at the local TLS
# listener a real deployment (or a local test of one) uses instead of plain
# HTTP. Generated by infra/tls/generate-local-cert.sh, gitignored, never the
# OS's own trust store: only this process, for this one host, trusts it,
# rather than installing a root CA that every other app on the machine
# would then trust too. Not resolved to API_VERIFY here at import time: a
# module-level filesystem check runs inside Temporal's workflow sandbox the
# moment anything reachable from a workflow imports this module, and that
# sandbox refuses `Path.is_file()` there ("__call__ on pathlib.Path.is_file
# restricted"). api_verify() below runs the same check, but only when an
# activity actually calls it.
API_CA_CERT = os.environ.get("MUNITAS_API_CA_CERT", "infra/tls/out/localhost.pem")


def api_verify() -> bool | str:
    """What to pass as httpx's `verify=` for a call to `API`.

    The cert file when it exists (trust exactly that, nothing else); `True`
    otherwise, which is also exactly correct for plain `http://` (`verify`
    is not consulted at all) and for a real deployment's CA-signed
    certificate (the system trust store already has it).
    """
    return API_CA_CERT if Path(API_CA_CERT).is_file() else True
MLFLOW = os.environ.get("MUNITAS_MLFLOW_URL", f"http://localhost:{PORTS['mlflow']}")
S3_ENDPOINT = os.environ.get("S3_ENDPOINT", f"http://localhost:{PORTS['seaweedfs_s3']}")
LABEL_STUDIO = os.environ.get("MUNITAS_LABEL_STUDIO_URL", f"http://localhost:{PORTS['label_studio']}")

# No BUCKET constant. The worker used to hold one and fall back to it whenever
# a caller did not name a bucket, which was right only while every tenant's
# objects were in the same place. The control plane answers with the bucket
# for the tenant whose data a run is processing, activities.py refuses a run
# whose carried bucket disagrees with that answer, and platform_client.py now
# requires the argument rather than defaulting it.
TASK_QUEUE = "munitas-pipeline"

# HuggingFace ingestion is network I/O, not GPU work, so it runs as a second
# worker on its own task queue rather than sharing the pipeline's, whose
# `max_concurrent_activities=1` exists specifically because the GPU cannot
# hold two models at once. A large or slow fetch should not have to wait
# behind a transcription, or the other way round.
HF_INGEST_TASK_QUEUE = "munitas-hf-ingest"

# Agent runs are neither GPU work nor the HuggingFace fetch's network I/O, so
# they get a third task queue: a stuck or slow agent run should not compete
# with either of the other two for its pool's threads.
AGENT_RUN_TASK_QUEUE = "munitas-agent-run"

# Script steps of an operator-registered DAG. Separate from TASK_QUEUE on
# purpose: that queue's worker runs with max_concurrent_activities=1
# because one GPU cannot hold two models, and a sandboxed script step needs
# no GPU at all. Sharing the queue would serialize two harmless scripts
# behind each other for no reason, the same argument that already put
# HuggingFace ingestion on its own queue above.
DAG_SCRIPT_TASK_QUEUE = "munitas-dag-scripts"

# The Docker-dependent half of the agent-run work, on its own task queue so a
# second worker can serve just this from inside the WSL2 distro, next to the
# Docker socket, while the pipeline, HuggingFace ingestion and native agent
# runs stay in the host worker on Windows. Only run_sandboxed_agent is routed
# here (worker/agent_run_workflow.py); AgentRunWorkflow itself and every other
# activity stay on AGENT_RUN_TASK_QUEUE. This is what lets a sandboxed run
# reach Docker at all on a machine where the daemon has no TCP listener the
# Windows side could use, without opening the socket over a port. See
# worker/sandbox_worker.py.
SANDBOX_TASK_QUEUE = os.environ.get(
    "MUNITAS_SANDBOX_TASK_QUEUE", "munitas-sandbox-run"
)

# Housekeeping (currently: sweeping stale probe tenants). Plain Postgres and
# S3 calls, nothing GPU- or model-related, so it gets its own small queue
# rather than sharing the pipeline's single-concurrency pool for the same
# reason HuggingFace ingestion does above: unrelated work should not wait
# behind each other.
HOUSEKEEPING_TASK_QUEUE = "munitas-housekeeping"
# A confirmed derivation (derivation_workflow.py). Its own queue so a query is never
# stuck behind the pipeline, which runs one activity at a time for the GPU.
DERIVATION_TASK_QUEUE = "munitas-derivation"
# The image a derivation's three containers run from (worker/derive/Dockerfile).
DERIVE_IMAGE = os.environ.get("MUNITAS_DERIVE_IMAGE", "munitas-derive-runner:1")

# The worker's one direct database connection. Everything else the pipeline
# produces goes through the control plane API (see `platform_client.py`'s
# docstring for why); this is the same accepted exception
# `run_pipeline.py`'s `ensure_actions()`/`ensure_tenant()` already use,
# because the control plane has no endpoint for these yet.
PG_DSN = os.environ.get(
    "MUNITAS_PG_DSN", f"postgresql://munitas:munitas@localhost:{PORTS['postgres']}/platform"
)

# Pipeline runs from this machine are verification runs, so they land in the
# canary tenant rather than beside the demonstration organisation. Override to
# point the worker at a real tenant.
TENANT = os.environ.get("MUNITAS_TENANT", "canary")

# Every folder the worker uses sits under one root, MUNITAS_DATA, set in .env
# and passed to the workers by start-dev.ps1. MUNITAS_CORPUS and MUNITAS_WORK
# override one folder each. There is no built-in root: a drive letter that
# suits one machine is not a default for anyone else. These are only ever
# used through require_work_dir() and require_corpus_dir() below, which
# refuse a value that cannot mean what it says on the OS actually running.
_DATA = os.environ.get("MUNITAS_DATA", "").strip().rstrip("/\\")
_CORPUS_DEFAULT = f"{_DATA}/synthetic" if _DATA else ""
_WORK_DEFAULT = f"{_DATA}/work" if _DATA else ""
CORPUS = Path(os.environ.get("MUNITAS_CORPUS", _CORPUS_DEFAULT))
WORK = Path(os.environ.get("MUNITAS_WORK", _WORK_DEFAULT))

_WORK_HOW_TO_SET = (
    "Set MUNITAS_DATA in .env to the folder that holds the platform's data; "
    "the work folder is MUNITAS_DATA/work, and MUNITAS_WORK overrides it.\n"
    "  Started by start-dev.ps1: that script passes both, translated for WSL "
    "where needed, so this means the translation failed. Check "
    "ConvertTo-WslPath in wsl-docker.ps1.\n"
    "  Started by Docker Compose (worker-lite): set MUNITAS_HOST_WORK_DIR in .env.\n"
    "  Started by hand inside WSL: export MUNITAS_WORK=/mnt/<drive>/<folder>/work"
)
_CORPUS_HOW_TO_SET = (
    "Set MUNITAS_DATA in .env to the folder that holds the platform's data; "
    "the corpus is MUNITAS_DATA/synthetic, and MUNITAS_CORPUS overrides it.\n"
    "  Inside WSL: export MUNITAS_CORPUS=/mnt/<drive>/<folder>/synthetic"
)


class RefusedPath(RuntimeError):
    """A configured directory that cannot mean what it says on this OS."""


class InsecureApiUrl(RuntimeError):
    """MUNITAS_API points off this machine over plain HTTP."""


def require_secure_api() -> None:
    """Refuse to start if MUNITAS_API sends this worker's traffic to the
    control plane -- including a person's HuggingFace token
    (hf_ingest_activities.py's `_token_for`) and the shared worker token
    (dag_activities.py, sandbox_run.py's `x-worker-token` header) -- over
    plain HTTP to somewhere other than this machine.

    localhost stays allowed unencrypted: that traffic never leaves the
    machine, so there is nothing on the wire for a plain HTTP request to
    expose. Once MUNITAS_API names a real host, the same traffic would
    cross a real network in cleartext unless it is HTTPS, so that is the
    one thing this checks. It does not (and cannot) verify the HTTPS
    endpoint is actually configured correctly, only that a real deployment
    was not left on the default meant for one machine.

    Called once, by worker/main.py, before anything else starts. Not at
    import: scripts that read `config.API` without ever calling it (the
    verify/ suite, one-off admin scripts) should not be refused a value
    they never intended to use insecurely.
    """
    from urllib.parse import urlsplit

    parsed = urlsplit(API)
    if parsed.scheme == "https" or parsed.hostname in ("localhost", "127.0.0.1"):
        return
    raise InsecureApiUrl(
        f"Refusing to start: MUNITAS_API is {API!r}, which sends every "
        "request this worker makes -- including a HuggingFace token and "
        "the shared worker token -- to a real network address over plain "
        "HTTP.\n"
        "  Point MUNITAS_API at an https:// URL instead. For local "
        "development, see infra/tls/generate-local-cert.sh and "
        "RUNBOOK.md's \"Local HTTPS between the worker and the API\" "
        "section.\n"
        "  If this really is meant to stay on one machine, set MUNITAS_API "
        "to a localhost or 127.0.0.1 address."
    )


def _refuse(var: str, raw: str | None, default: str, why: str, how: str) -> RefusedPath:
    if raw is None and not default:
        shown = "not set, and neither is MUNITAS_DATA"
    elif raw is None:
        shown = f"not set, so {default!r} under MUNITAS_DATA was tried"
    else:
        shown = f"set to {raw!r}"
    return RefusedPath(f"Refusing to start: {var} is {shown}, and {why}.\n{how}")


def _absolute(var: str, default: str, how: str) -> Path:
    # Read the environment again rather than trusting WORK/CORPUS, because
    # Path("") is "." and the empty string would already be gone.
    raw = os.environ.get(var)
    value = default if raw is None else raw
    if raw is None and not default:
        raise _refuse(var, raw, default, "so there is no folder to use", how)
    if not value.strip():
        raise _refuse(var, raw, default, "an empty value is not a path", how)
    path = Path(value)
    if not path.is_absolute():
        # On Linux "P:" is an ordinary folder name, so a Windows path would
        # otherwise be created underneath whatever directory the process
        # started in. That is where the stray P: folder in the repo came from.
        if re.match(r"^[A-Za-z]:[\\/]", value) and os.name != "nt":
            why = "that is a Windows path, which is not absolute on this OS"
        else:
            why = "it is not an absolute path"
        raise _refuse(var, raw, default, why, how)
    return path


def require_work_dir() -> Path:
    """Return the work directory, creating it, or refuse with what to set.

    Called once by each worker process before it connects to Temporal
    (worker/main.py, worker/lite_worker.py, worker/sandbox_worker.py). Not at
    import: this module is also imported by scripts that never touch WORK.
    """
    path = _absolute("MUNITAS_WORK", _WORK_DEFAULT, _WORK_HOW_TO_SET)
    try:
        path.mkdir(parents=True, exist_ok=True)
        probe = path / f".write-check-{os.getpid()}"
        probe.write_bytes(b"")
        probe.unlink()
    except OSError as exc:
        raise _refuse("MUNITAS_WORK", os.environ.get("MUNITAS_WORK"), _WORK_DEFAULT,
                      f"it cannot be used as a writable directory ({exc})",
                      _WORK_HOW_TO_SET) from exc
    return path


def require_corpus_dir() -> Path:
    """Return the corpus directory, or refuse with what to set.

    A corpus is read and never created, so unlike the work directory it must
    already exist. Called by run_pipeline.py and schedule_pipeline.py before a
    workflow starts, because a wrong corpus otherwise surfaces much later,
    inside the ingest activity, as "no records found".
    """
    path = _absolute("MUNITAS_CORPUS", _CORPUS_DEFAULT, _CORPUS_HOW_TO_SET)
    if not path.is_dir():
        raise _refuse("MUNITAS_CORPUS", os.environ.get("MUNITAS_CORPUS"), _CORPUS_DEFAULT,
                      "no directory exists there", _CORPUS_HOW_TO_SET)
    return path

# The pipeline runs inside the boundary, so it holds the one role whose floor
# reaches RAW. Nothing else in the system does.
PIPELINE_ROLE = "pipeline_action"
# No storage key here. The pipeline reads what it wrote earlier with a key the control plane gives it for the organisation it is
# working for (platform_client.pipeline_s3), one per organisation, and not one set in this process's environment that opened
# every organisation's bucket.
# No PIPELINE_PRINCIPAL constant. One worker process serves every tenant's
# runs (TASK_QUEUE above is one shared queue, not one per tenant), so a
# single config value naming the workload to assert would claim whichever
# tenant that value happened to name while actually processing a different
# one's data -- the exact failure _tenant() in activities.py already
# stopped config.TENANT from causing for sealing. worker/activities.py's
# _pipeline_principal() derives it per run instead, from the tenant the run
# actually belongs to (`<tenant>-pipeline`, item 63's naming convention).

# 8 GB of VRAM is the binding constraint, so models load and unload in sequence
# rather than staying resident. int8_float16 keeps large-v3 to roughly 3 to 4 GB.
WHISPER_MODEL = os.environ.get("WHISPER_MODEL", "large-v3")
WHISPER_COMPUTE = os.environ.get("WHISPER_COMPUTE", "int8_float16")
# Passed straight to transcribe_backend.load_backend(), which is the only
# thing that reads this value -- see that module's own docstring for which
# devices are registered today ("cuda", "cpu") and what adding another one
# (e.g. "mps") actually requires.
WHISPER_DEVICE = os.environ.get("WHISPER_DEVICE", "cuda")

GLINER_MODEL = os.environ.get("GLINER_MODEL", "urchade/gliner_medium-v2.1")
SPACY_MODEL = os.environ.get("SPACY_MODEL", "en_core_web_lg")

# Shared secret sent to GET /agents/{id}/versions/{id}/code (agent_upload.py).
# Must match MUNITAS_WORKER_TOKEN on the munitas-api container, set once,
# in the same place, and read by both sides from the same env var name so
# there is only one value to keep in sync rather than two.
WORKER_TOKEN = os.environ.get(
    "MUNITAS_WORKER_TOKEN", "dev-worker-token-not-for-production"
)

# The Compose network a sandboxed agent run's own container is attached to
# (docker-compose.yml's `agentnet`, `internal: true`, no gateway). Docker
# Compose prefixes network names with the project name (`name: munitas` at
# the top of docker-compose.yml) unless the network sets its own `name:`,
# which none of these three do, confirmed against a running stack with
# `docker network ls`, not guessed.
AGENTNET = os.environ.get("MUNITAS_AGENTNET", "munitas_agentnet")

# Where a sandboxed run reaches the control plane from inside agentnet: the
# container-network service name, not localhost: this address is resolved
# from inside the sandbox container, which is not this host process.
SANDBOX_API = os.environ.get("MUNITAS_SANDBOX_API", "http://munitas-api:8000")

# The Compose network the staging container reaches SeaweedFS on
# (docker-compose.yml's `data` network; munitas-api is also a member,
# which is how the staging container can reach both). Never agentnet.
# Confirmed against a running stack with `docker network ls`
# (`munitas_data`), the same way AGENTNET above already was.
DATA_NETWORK = os.environ.get("MUNITAS_DATA_NETWORK", "munitas_data")


# ------------------------------------------------------------------ logs --
#
# A worker's window is not a record: close it and everything it said is gone.
# Twice that lost the one piece of evidence an investigation needed, so each
# worker also writes to <MUNITAS_LOG_DIR or MUNITAS_DATA/logs>/<worker>.log,
# rolled over at 10 MB with five kept, so logs cannot fill the disk.

LOG_FORMAT = "%(asctime)s  %(levelname)-7s %(name)s  %(message)s"


def configure_logging(worker: str):
    """Log to the console and, where a log folder is configured, to a file.

    Returns the file's path, or None with the reason already logged. A folder
    that is not an absolute path on this OS is refused rather than created,
    for the same reason require_work_dir() refuses one: a Windows path read
    on Linux is a relative folder name, and would be created wherever the
    worker happened to start.
    """
    import logging
    from logging.handlers import RotatingFileHandler

    handlers: list = [logging.StreamHandler()]
    folder = os.environ.get("MUNITAS_LOG_DIR", "").strip() or (f"{_DATA}/logs" if _DATA else "")
    path, problem = None, None
    if not folder:
        problem = "no log folder is configured (MUNITAS_LOG_DIR or MUNITAS_DATA), so this worker logs to the console only"
    elif not Path(folder).is_absolute():
        problem = f"log folder {folder!r} is not an absolute path on this OS, so this worker logs to the console only"
    else:
        path = Path(folder) / f"{worker}.log"
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            handlers.append(RotatingFileHandler(path, maxBytes=10_000_000,
                                                backupCount=5, encoding="utf-8"))
        except OSError as exc:
            path, problem = None, f"cannot write to {folder!r} ({exc}), so this worker logs to the console only"
    logging.basicConfig(level=logging.INFO, format=LOG_FORMAT, handlers=handlers, force=True)
    log = logging.getLogger(f"munitas.worker.{worker}")
    if path:
        log.info("logging to %s", path)
    else:
        log.warning(problem)
    return path


def temporal_runtime():
    """A Temporal runtime whose own connection messages (retries, refusals)
    go through Python logging, and so into the log file, instead of only to
    the console. Warnings and above."""
    import logging

    from temporalio.runtime import (LogForwardingConfig, LoggingConfig, Runtime,
                                    TelemetryConfig, TelemetryFilter)

    return Runtime(telemetry=TelemetryConfig(logging=LoggingConfig(
        filter=TelemetryFilter(core_level="WARN", other_level="WARN"),
        forwarding=LogForwardingConfig(logger=logging.getLogger("temporalio.core")),
    )))
